### ISSUE TITLE
A tic tac toe game

### ISSUE THREAD

**Issue by amuradyan** [dekanat/whiteboard#5]
I propose we try a tic tac toe game. We can use any drawing tool, branch for each move and open PRs.

What say you @mushegha ?

_Originally posted by @amuradyan in https://github.com/dekanat/whiteboard/issues/1#issuecomment-1019567744_

**Comment by mushegha** [comment]
I never lost in that game. You start?

**Comment by mushegha** [comment]
Do you need a layout to start?
![image](https://user-images.githubusercontent.com/25614707/150698279-bc27a5db-34b2-4c9d-8316-fdcef939a552.png)

**Comment by amuradyan** [comment]
I've created a [_root_](https://github.com/dekanat/whiteboard/tree/5-a-tic-tac-toe-game) branch for the game, and will play on a dedicated [branch for X](https://github.com/dekanat/whiteboard/tree/5-a-tic-tac-toe-game-x) /I play X, btw/.

I will move /open a PR to _root_/ and you'll acknowledge it /merge the PR/ and respond /open a PR to _root_/.

Ոնց ա՞

**Comment by mushegha** [comment]
Good. Open all the PRs.

**Comment by mushegha** [comment]
> Good. Open **all** the PRs.

**Comment by mushegha** [comment]
Nevermind

**Comment by amuradyan** [comment]
I don't see, why that needs to be done, but I have nothing against it. Go ahead and open it.

**Comment by mushegha** [comment]
@amuradyan gg

**Comment by amuradyan** [comment]
gg

**Comment by mushegha** [comment]
![Winner](https://raw.githubusercontent.com/dekanat/whiteboard/5-a-tic-tac-toe-game/tic-tac-toe/board.png)
